### ISSUE TITLE
Instructions for generating custom models

### ISSUE THREAD

**Issue by anaisbetts** [wingman-jr-addon/wingman_jr#181] opened 2022-11-19 10:17 UTC
Are there instructions for replacing the model with a different trained model? Something like open-sourcing the tools to generate the model but without the training content?

**Comment by wingman-jr-addon** [comment] 2022-11-19 15:19
There are the two main repositories here - this one for the addon itself, and then the one for the model over at https://github.com/wingman-jr-addon/model
For replacing a model in the addon, the discussion can continue here but that's a smaller part of the big picture. For a discussion on the tools and creation of the model itself, etc. can you please open a ticket over on the model repo? Much of that is not released but if there is interest in parts of it I think the discussion can best be focused there. Thanks!

**Comment by anaisbetts** [comment] 2022-11-20 10:27
@wingman-jr-addon I think you can [move this ticket](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) via GitHub

**Comment by wingman-jr-addon** [comment] 2022-11-20 20:22
Well I was thinking it might make more sense to split it, because there are the two halves so to speak.
See the other ticket here: https://github.com/wingman-jr-addon/model/issues/5

As noted previously, we can keep the "replacing the model in the addon" part in this thread!

**Comment by wingman-jr-addon** [comment] 2022-11-20 21:00
So to replace the model, a few key things are needed. See the other issue for the model side of things.

- Update the model weights/schema. The folder sqrxr_112_graphopt is the output of the Tensorflow.js model conversion tool.
- Update the references that point to the model.
- Update the ROC_VALUES in roc.js so that the various regression thresholds are updated. These are discussed on the model side of this process, but basically correspond to various points on the curve here: https://github.com/wingman-jr-addon/model/blob/master/sqrxr_112/post_roc.png

This commit (https://github.com/wingman-jr-addon/wingman_jr/commit/5bc717cf5086c699d005a73dfda8a860ed3fbb71#diff-52058d2178d79ce251c8c97fdcab94fb9cf13005b8060eb43fdb07c68cec077d) shows the artifacts that get updated during a new model integration.

**Comment by Refizul84** [comment] 2022-11-24 13:59
Hello it's about the update original Wave Link code to v1.6

I do not get it

Would it be possible to download it like the last ones?

**Comment by wingman-jr-addon** [comment] 2022-11-25 03:46
@Refizul84 I'm not quite sure how your comment is related to this issue - can you explain what you meant?

**Comment by anaisbetts** [comment] 2022-11-26 08:59
@wingman-jr-addon I believe @Refizul84 is following me around and posting about an unrelated project I maintain - feel free to delete his comment

**Comment by wingman-jr-addon** [comment] 2022-11-27 03:05
Thanks @anaisbetts - @Refizul84 I'll pull your comment down for now but feel free to jump into the conversation on this issue if you had a question about the model here instead.
@anaisbetts I think most of the "interesting stuff" from your perspective is over on the issue https://github.com/wingman-jr-addon/model/issues/5 - let me know if you have questions here or there.

**Comment by wingman-jr-addon** [comment] 2023-01-16 04:00
@anaisbetts Given no further response, I'll close this for now. Please request more specifics either here or on the other issue if desired.

**Closed by wingman-jr-addon** 2023-01-16 04:00 UTC
