### ISSUE TITLE
Support for chrome

### ISSUE THREAD

**Issue by kiran-collab** [wingman-jr-addon/wingman_jr#121] opened 2021-03-27 13:23 UTC
@wingman-jr-addon 
can this extension be ported to chrome. Can you guide regarding the same.
Thankyou

**Comment by wingman-jr-addon** [comment] 2021-03-27 21:28
@kiran-collab This is actually a duplicate of #2 - I looked into it but if you tried to do a port via the same `webRequest` API's it simply won't be possible because Chrome doesn't have them. nsfw-filter (as you are familiar with I know already) does support Chrome; theirs works by hooking into the DOM instead. It's a different approach with different strengths and weaknesses, but probably the main viable approach if you were to support Chrome. I'm going to close this one as I've already looked into extensively but feel free to ask if you have any further questions - and do read through #2 as it will probably answer some questions you might have.

**Closed by wingman-jr-addon** 2021-03-27 21:28 UTC
